jobs:
  build-11:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Compile Java ${{ matrix.java }}
      run: mvn clean compile -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true -D maven.javadoc.skip=true
    - continue-on-error: true
      name: Run Tests ${{ matrix.java }}
      run: 'mvn test -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Build Test Report ${{ matrix.java }}
      run: 'mvn surefire-report:report-only -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        mvn site -D generateReports=false -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Results ${{ matrix.java }}
        path: target/surefire-reports/
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Report ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Report ${{ matrix.java }}
        path: target/site/
    - continue-on-error: true
      name: Package Jar ${{ matrix.java }}
      run: mvn clean package -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Package Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Package Jar ${{ matrix.java }}
        path: target/*.jar
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
      max-parallel: 1
  build-17:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Compile Java ${{ matrix.java }}
      run: mvn clean compile -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true -D maven.javadoc.skip=true
    - continue-on-error: true
      name: Run Tests ${{ matrix.java }}
      run: 'mvn test -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Build Test Report ${{ matrix.java }}
      run: 'mvn surefire-report:report-only -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        mvn site -D generateReports=false -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Results ${{ matrix.java }}
        path: target/surefire-reports/
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Report ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Report ${{ matrix.java }}
        path: target/site/
    - continue-on-error: true
      name: Package Jar ${{ matrix.java }}
      run: mvn clean package -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Package Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Package Jar ${{ matrix.java }}
        path: target/*.jar
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
      max-parallel: 1
  build-1_6:
    name: Java 1.6
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.6
    - continue-on-error: true
      name: Compile Java 1.6
      run: 'mkdir -p target/classes

        javac -version

        javac -source 1.6 -target 1.6 -d target/classes/ src/main/java/org/json/*.java

        '
    - continue-on-error: true
      name: Create java 1.6 JAR
      run: 'jar cvf target/org.json.jar -C target/classes .

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload JAR 1.6
      uses: actions/upload-artifact@v3
      with:
        name: Create java 1.6 JAR
        path: target/*.jar
  build-21:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Compile Java ${{ matrix.java }}
      run: mvn clean compile -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true -D maven.javadoc.skip=true
    - continue-on-error: true
      name: Run Tests ${{ matrix.java }}
      run: 'mvn test -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Build Test Report ${{ matrix.java }}
      run: 'mvn surefire-report:report-only -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        mvn site -D generateReports=false -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Results ${{ matrix.java }}
        path: target/surefire-reports/
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Report ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Report ${{ matrix.java }}
        path: target/site/
    - continue-on-error: true
      name: Package Jar ${{ matrix.java }}
      run: mvn clean package -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Package Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Package Jar ${{ matrix.java }}
        path: target/*.jar
    strategy:
      fail-fast: false
      matrix:
        java:
        - 21
      max-parallel: 1
  build-8:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Compile Java ${{ matrix.java }}
      run: mvn clean compile -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true -D maven.javadoc.skip=true
    - continue-on-error: true
      name: Run Tests ${{ matrix.java }}
      run: 'mvn test -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Build Test Report ${{ matrix.java }}
      run: 'mvn surefire-report:report-only -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        mvn site -D generateReports=false -D maven.compiler.source=${{ matrix.java
        }} -D maven.compiler.target=${{ matrix.java }}

        '
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Results ${{ matrix.java }}
        path: target/surefire-reports/
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Report ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Test Report ${{ matrix.java }}
        path: target/site/
    - continue-on-error: true
      name: Package Jar ${{ matrix.java }}
      run: mvn clean package -D maven.compiler.source=${{ matrix.java }} -D maven.compiler.target=${{
        matrix.java }} -D maven.test.skip=true -D maven.site.skip=true
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Package Results ${{ matrix.java }}
      uses: actions/upload-artifact@v3
      with:
        name: Package Jar ${{ matrix.java }}
        path: target/*.jar
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
      max-parallel: 1
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___pipeline.yml
